elasticsearch:
  container_name: ElasticSearch    
  image: elasticsearch:2.3
  volumes:
    - ./../../../../volumes/elasticsearch:/usr/share/elasticsearch/data
  networks:
    - log
  ports:
    - "9200:9200"